title: Data Activism Program
theme: just-the-docs

url: https://just-the-docs.github.io
favicon_ico: /favicon (1).ico

aux_links:
  Slides: https://liberatorycomputing.github.io/DataActivismProgram/Slides.html
  Videos: https://liberatorycomputing.github.io/DataActivismProgram/Videos.html


callouts:
  note:
    title: NOTE
    color: red
